### ISSUE TITLE
Not compatible with angular.js v1.3.0-rc.0 sonic-boltification

### ISSUE THREAD

**Issue by ryanhart2** [btford/angular-modal#26]
$animate.leave no longer accepts a callback as a second parameter, but instead returns a promise.

In the code shown below, the anonymous function passed to $animate.leave is never executed. As a result of the element variable not being set to null, the modal is not displayed on subsequent activate calls.

```javascript
function deactivate () {
  var deferred = $q.defer();
  if (element) {
    $animate.leave(element, function () {
      scope.$destroy();
      element = null;
      deferred.resolve();
    });
  } else {
    deferred.resolve();
  }
  return deferred.promise;
}
```

This is the [commit](https://github.com/angular/angular.js/commit/bf0f5502b1bbfddc5cdd2f138efd9188b8c652a9) that made the breaking change.

**Comment by btford** [comment]
Should be fixed in v0.5
