### ISSUE TITLE
Instantiating multiple times is broken in Angular 1.3.2

### ISSUE THREAD

**Issue by cobalamin** [btford/angular-modal#32]
I noticed that the modal only shows up, or is created at all, at the first call of `activate` in Angular 1.3.
By that I don't mean calling `activate` twice in succession (which doesn't make a lot of sense), but calling it in a way that I'd expect to work:

```js
modal.activate(); // shows up
asyncOperation().then(function() {
  modal.deactivate();
  modal.activate(); // does not show up
  otherAsyncOperation.then(modal.deactivate);
});
```

I first thought it might be a CSS issue on my end, but putting a test statement `console.log('instantiating loading ctrl');` inside the modal's controller showed that the controller won't be instantiated again after the modal is closed the first time.

All this, however, works as expected when I use Angular 1.2.x instead.

**Comment by btford** [comment]
Should be fixed in v0.5.
