### ISSUE TITLE
Modal service "active" value not updated instantly

### ISSUE THREAD

**Issue by MarkusPint** [btford/angular-modal#33]
Hello,
I like the module so far, however I am having a little problem with its' implementation.

1. I have a main controller, where I am watching the modal service "active" value. This watcher changes a scope value in that controller in order to reflect in the view whether this modal is open or not.

    $scope.$watch( function() { return Modal.active(); },
        function(newValue) {
            $scope.ModalActive = newValue;
        }
    );

2.  In the controller of the modal I have a function:

    $scope.closeModal = function() {
        Modal.deactivate();
    };

3. When this function is activated the modal does close, however the watcher in the main controller does not pick up the "active" value change.

I understand this is an async problem. A quick fix could be something with $timeout, but I am sure there is a more elegant solution. Any ideas?

**Comment by btford** [comment]
This is expected behavior.

Each of these methods returns a promise that you can use to know when a state change finishes.
