### ISSUE TITLE
Not adding variables through modalService.activate

### ISSUE THREAD

**Issue by pdrf** [btford/angular-modal#40]
I upgraded my angular to 1.3.15 and the btfmodal to the latest and when opening a modal that has params from the parent scope it doesn't seem to be passing them.

I'm doing something like:
`newModalService.activate({
    id: itemId
});`

I believe there is an issue with the new version 0.5.0 on the attach function when doing `locals.$scope = scope` and `$controller(controller, locals)` because locals are not being added to the $scope.

Reverted to 0.4.0 and everything is fine.

Has anyone had the same problem?

**Comment by phillip-haydon** [comment]
Yeah same problem.

Changing:

```
      if (controller) {
        if (!locals) {
          locals = {};
        }
        locals.$scope = scope;
        var ctrl = $controller(controller, locals);
        if (controllerAs) {
          scope[controllerAs] = ctrl;
        }
      }
```

to

```
      if (controller) {
        if (!locals) {
          locals = {};
        }
        for (var prop in locals) {
            scope[prop] = locals[prop];
        }
        locals.$scope = scope;
        var ctrl = $controller(controller, locals);
        if (controllerAs) {
          scope[controllerAs] = ctrl;
        }
      }
```

Solved the issue for me. 

Need @btford to take a look tho because I don't completely understand whats happening.

**Comment by pdrf** [comment]
Exactly, my solution was a bit different, maybe more clean:

```
      if (controller) {
        if (!locals) {
          locals = {};
        }
        for (var prop in locals) {
            scope[prop] = locals[prop];
        }
        var ctrl = $controller(controller, {$scope: scope});
        if (controllerAs) {
          scope[controllerAs] = ctrl;
        }
      }
```

basically params are not getting set to the $scope.

**Comment by stryju** [comment]
after small investigation, it turns out that the `activate`'s behavior changed - if the controller is present, `activate` will pass the hash to controller's DI

take a look @ [specs](https://github.com/btford/angular-modal/blob/ccb914042a1e1f5648074de65f1f19e698b62c5d/modal.spec.js#L117-L147)

the problem is with the docs, it seems

**Comment by pdrf** [comment]
@stryju nice catch, you're right. thanks
