### ISSUE TITLE
So hard to use and it seems unfinished

### ISSUE THREAD

**Issue by sleaze** [btford/angular-modal#41]
This library feels difficult to use and reason about, and overall it seems unfinished.   How can I make <ESC> close the modal?

For now I'm going with https://github.com/vesparny/angular-fancy-modal since it works great out the box..

**Comment by mathewbergt** [comment]
As stated in the documentation:

> modalService.deactivate
> 
> Removes the modal (DOM and scope) from the DOM. Returns a promise that resolves once the modal is removed.

In other words, `myModal.deactivate()`.

**Comment by sleaze** [comment]
OK THANK YOU BERG.
