### ISSUE TITLE
Overflow: hidden; on the body

### ISSUE THREAD

**Issue by sergonius** [btford/angular-modal#45]
I think that would make sense to have in a modal plugin as a default option.

**Comment by btford** [comment]
I don't think components should reach out of their sandbox like that.

Adding style to the body should be largely left up to the application developer.

**Comment by graup** [comment]
I was just looking for the same thing. Any idea how to implement this?

We'd need a single place to add the class if _any_ modal is visible. Maybe a wrapper around this factory?

**Comment by graup** [comment]
I finally just [forked the plugin and added two lines of code](https://github.com/productgang/angular-modal/commit/4cee5b3900d5210a3126ea96b031569471773a13). Too much headache trying to work around it otherwise.
